# serverless.yml

service: theservice
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app: 
    name: ageoftesting
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'